assethost:
  production: //junction-assets.s3.amazonaws.com
tumblr:
  blog: kriszor.tumblr.com
  key: <%= ENV['TUMBLR'] %>
  rss: http://kriszor.tumblr.com/rss
twitter:
  access_key: <%= ENV['TWITTER_ACCESS_KEY'] %>
  access_secret: <%= ENV['TWITTER_ACCESS_SECRET'] %>
  key: <%= ENV['TWITTER_KEY'] %>
  secret: <%= ENV['TWITTER_SECRET'] %>
github:
  id: <%= ENV['GITHUB_ID'] %>
  key: <%= ENV['GITHUB_ACCESS_TOKEN'] %>
  password: <%= ENV['GITHUB_SECRET'] %>
  username: krisrang
lastfm:
  key: <%= ENV['LAST_KEY'] %>
  username: noin
instagram:
  id: <%= ENV['INSTAGRAM_ID'] %>
  secret: <%= ENV['INSTAGRAM_SECRET'] %>
  access_token: <%= ENV['INSTAGRAM_ACCESS_TOKEN'] %>
  access_id: <%= ENV['INSTAGRAM_ACCESS_ID'] %>
foursquare:
  access_token: <%= ENV['FSQ_ACCESS_TOKEN'] %>
steam:
  key: <%= ENV['STEAM_KEY'] %>
site:
  description: Personal site of Kristjan Rang. Development. Gaming. Stuff.
  title: Kristjan Rang
  keywords: Kristjan Rang, krisrang, kriszor, kreu, pawdrop
  rss_enabled: true
disqus:
  enabled: true
  shortname: kreumain
